### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by mattjanus** [nettofarah/mysql-schema-ts#5]
tried running your example
```
npx mysql-schema-ts mysql://root@xxx:3306/yyy
npx: installed 72 in 7.324s
Unexpected token function
```

**Comment by nettofarah** [comment]
Which version of mysql are you using?
I was able to run it fine with `5.7.29`

**Comment by mattjanus** [comment]
mysqld  Ver 5.7.30-0ubuntu0.18.04.1 for Linux on x86_64 ((Ubuntu)). ran the command from my macbook.
