### ISSUE TITLE
tinyint should probably be a number not a  boolean

### ISSUE THREAD

**Issue by naseemkullah** [nettofarah/mysql-schema-ts#9]
https://github.com/nettofarah/mysql-schema-ts/blob/711b6419e227aea7e2f22ce8777768e823869f91/src/column-map.ts#L42-L43

There are cases where it can go beyond 0 or 1 (up to 255), thoughts?

**Comment by naseemkullah** [comment]
https://github.com/nettofarah/mysql-schema-ts/pull/10 created if maintainers agree

**Comment by naseemkullah** [comment]
https://github.com/mysqljs/mysql#type-casting

Also see https://github.com/SweetIQ/schemats/issues/116#issue-581401801

**Comment by naseemkullah** [comment]
Bump

**Comment by nettofarah** [comment]
That's a good idea! I'm down with it :)
